### ISSUE TITLE
use fotorama on each gallery

### ISSUE THREAD

**Issue by kfrankc** [dailybruin/caeruleum#29]
Using the fotorama library, create the gallery page for each gallery.

**Comment by zeehang** [comment]
<img width="1279" alt="screen shot 2016-02-24 at 8 14 08 pm" src="https://cloud.githubusercontent.com/assets/15135987/13309603/421d7e86-db33-11e5-8a5e-892edcaf390f.png">

Gallery is cut off, caused by margin from
.db-content .db-story div
which i can't find in any of the caeruleum files

FIXED VERSION (with inspect element margin unchecked)
<img width="1278" alt="screen shot 2016-02-24 at 8 17 03 pm" src="https://cloud.githubusercontent.com/assets/15135987/13309650/932af09c-db33-11e5-8e5c-ecfa6f361ab5.png">

**Comment by kfrankc** [comment]
After merging, this issue came up. I will look into it, but spectrum and navbar are now at the bottom of the page. 
![screenshot from 2016-02-24 21 11 36](https://cloud.githubusercontent.com/assets/7086890/13310505/579a4020-db3b-11e5-8c0a-87dbf8900bc3.png)
